name: Release JSON for awesome-data builds

on:
  schedule:
    - cron: "0 3 * * *"    # daily at 03:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: jo-chemla
          repo: awesome-selfhosted-data
          base: master   # upstream branch
          head: master   # your fork branch
          merge_method: merge
          ignore_fail: false # choose whether merge will fail if no new commits to pull and merge, or do one release per day no matter what
          retry_after: 5
          retries: 2

  build-and-release:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge software/*.yml into software.json via yq
        uses: mikefarah/yq@master
        with:
          # cmd: yq ea '[.] as $item ireduce ([]; . *+ $item )' software/*.yml | yq -o=json -I 2 '{"softwares":.}' > software.json
          cmd: |
            yq ea '[.] as $item ireduce ([]; . *+ $item ) | {"softwares": .}' software/*.yml -o=json -I=2 > software.json
            && yq ea '[.] as $item ireduce ([]; . *+ $item ) | {"tags": .}' tags/*.yml -o=json -I=2 > tags.json
            && yq ea '[.] as $item ireduce ([]; . *+ $item ) | {"platforms": .}' platforms/*.yml -o=json -I=2 > platforms.json
            && yq ea -o=json -I=2 licenses-nonfree.yml > licenses-nonfree.json
            && yq ea -o=json -I=2 licenses.yml > licenses.json
      - name: Raw dump software.json
        run: cat software.json

      - name: Get date for release
        id: date
        run: echo "today=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.today }}
          name: "v${{ steps.date.outputs.today }}"
          files: software.json

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: github.ref_type == 'tag'
      #   with:
      #     files: software.json
