name: Release JSON for awesome-data builds

on:
  schedule:
    - cron: "0 3 * * *"    # daily at 03:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: jo-chemla
          repo: awesome-selfhosted-data
          base: master   # upstream branch
          head: master   # your fork branch
          merge_method: merge
          ignore_fail: false # choose whether merge will fail if no new commits to pull and merge, or do one release per day no matter what
          retry_after: 5
          retries: 2

  build-and-release:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge software/*.yml into software.json via yq
        uses: mikefarah/yq@master
        with:
          # cmd: yq ea '[.] as $item ireduce ([]; . *+ $item )' software/*.yml | yq -o=json -I 2 '{"softwares":.}' > software.json
          cmd: |
            yq ea '[.] as $item ireduce ([]; . *+ $item ) | {"softwares": .}' software/*.yml -o=json -I=2 > software.json
            yq ea '[.] as $item ireduce ([]; . *+ $item ) | {"tags": .}' tags/*.yml -o=json -I=2 > tags.json
            yq ea '[.] as $item ireduce ([]; . *+ $item ) | {"platforms": .}' platforms/*.yml -o=json -I=2 > platforms.json
            yq -o=json -I=2 '{"licenses-nonfree": .}' licenses-nonfree.yml > licenses-nonfree.json
            yq -o=json -I=2 '{"licenses": .}' licenses.yml > licenses.json
            # merge into awesome-selfhosted-data.json
            yq eval-all -p=json -o=json -I=2 '. as $item ireduce ({}; . * $item )' software.json tags.json platforms.json licenses-nonfree.json licenses.json > awesome-selfhosted-data.json
      # - name: Raw dump software.json
      #   run: cat software.json

      - name: Get date for release
        id: date
        run: echo "today=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      # Extend the JSON awesome-selfhosted-data.json to add eg added_date
      - name: Download previous release JSON
        run: |
          curl https://github.com/jo-chemla/awesome-selfhosted-data/releases/latest/download/awesome-selfhosted-data-extended.json -o latest-release-awesome-selfhosted-data-extended.json
      - name: Merge software/*.yml into software.json via yq
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval-all '
              . as $item ireduce ({}; . *+ {
                "softwares": ($item.softwares | map(. + {"added-date": "2025-10-14"}))
              })
            ' latest-release-awesome-selfhosted-data-extended.json software.json > awesome-selfhosted-data-extended.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.today }}
          name: "v${{ steps.date.outputs.today }}"
          body: |
            Download JSON data for latest release via this link: [awesome-selfhosted-data.json](https://github.com/jo-chemla/awesome-selfhosted-data/releases/latest/download/awesome-selfhosted-data.json) and [awesome-selfhosted-data-extended.json](https://github.com/jo-chemla/awesome-selfhosted-data/releases/latest/download/awesome-selfhosted-data-extended.json)
          # files: *.json
          files: | 
            software.json
            tags.json
            platforms.json
            licenses-nonfree.json
            licenses.json
            awesome-selfhosted-data.json
            awesome-selfhosted-data-extended.json

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: github.ref_type == 'tag'
      #   with:
      #     files: software.json
